### ISSUE TITLE
Set up travis

### ISSUE THREAD

**Issue by hukkin** [fiatjaf/bech32#2]
Now that we have a .travis.yml, we should enable it in Github. I believe the procedure is as follows:
1. Set up the free plan at https://github.com/marketplace/travis-ci (if not already done).
2. Go to https://github.com/settings/installations/ and configure Travis-CI settings. Enable travis for `fiatjab/bech32`

This can only be done by @fiatjaf

**Comment by fiatjaf** [comment]
It is there, but it is not building: https://travis-ci.org/fiatjaf/bech32

**Comment by hukkin** [comment]
@fiatjaf I triggered travis with a test MR. It seems to work fine. The proper URL seems to be https://travis-ci.com/fiatjaf/bech32 so `com` not `org`.

Btw. if you could make a PyPI release with the type annotations I would be very thankful!

**Comment by fiatjaf** [comment]
Ok, done.
Thank you!
